version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
    reviewers:
      - "Spissable"
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
    groups:
      npm-packages:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "docker images"
    reviewers:
      - "Spissable"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
